### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ananinys** [alvin0319/Crossbow#1]
when you improve the crossbow on the enchantment table, the crossbow does not work and it does not move in the inventory, but remains until you clear the inventory of the irok

**Comment by alvin0319** [comment]
Currently enchantments except multishot and quick charge aren't working.

**Comment by ananinys** [comment]
As well as a crossbow kills in private :D

**Comment by alvin0319** [comment]
What do you mean?

**Comment by ananinys** [comment]
the player can kill with a crossbow, despite the private

**Comment by alvin0319** [comment]
I don't understand thd word `private`

**Comment by ananinys** [comment]
Private region
