### ISSUE TITLE
break block glitch

### ISSUE THREAD

**Issue by zpwrd** [alvin0319/Crossbow#4]
when do you start breaking the block with a crossbow, the block breaks visually, but it will be like a phantom. you enter to the place of the broken block and start getting damage from suffocation.
https://www.mediafire.com/file/m4j9mrzf5uqbyll/2021-07-15_20-25-57.mkv/file

**Comment by alvin0319** [comment]
Upload video on GitHub or YouTube so that I can see it, I don't want to download file.

**Comment by zpwrd** [comment]
https://youtu.be/fTu64gpkVvc

**Comment by zpwrd** [comment]
> Upload video on GitHub or YouTube so that I can see it, I don't want to download file.

https://youtu.be/fTu64gpkVvc

**Comment by MrBlasyMSK** [comment]
> Upload video on GitHub or YouTube so that I can see it, I don't want to download file.

That is not a crossbow bug, I do not have that plugin and the same thing happens with the flashlights when placing them on the ceiling
